name: Node CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [10.x, 12.x]
        steps:
            -   uses: actions/checkout@v1
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}
            -   name: Create DB
                run: |
                    mysql -uroot -proot -e "CREATE DATABASE contentry_test CHARACTER SET utf8 COLLATE utf8_unicode_ci;"
            -   uses: borales/actions-yarn@v2.0.0
                with:
                    cmd: install # will run `yarn install` command
            -   uses: borales/actions-yarn@v2.0.0
                with:
                    cmd: build # will run `yarn build` command
            -   uses: borales/actions-yarn@v2.0.0
                with:
                    cmd: test # will run `yarn test` command
            -   name: npm install, lint and test
                run: |
                    yarn install
                    yarn lint
                    yarn test
                    yarn build
                env:
                    CI: true
